#ifndef SIGNALACCESSTEST_H
#define SIGNALACCESSTEST_H

#define SIGNAL_ACCESS_TEST_ENABLED       (0)

#if SIGNAL_ACCESS_TEST_ENABLED

int signalAccessorTest(void);

#endif //SIGNAL_ACCESS_ENABLED

#endif // SIGNALACCESSTEST_H
